name: BetterAlias
main: com.ne0nx3r0.betteralias.BetterAlias
version: ${project.version}
api-version: ${spigot.api.version}
database: false
description: Command alias system
commands:
   bareload:
      description: Reloads the aliases.yml file
permissions:
    BetterAlias.reload:
      description: Allows reloading BetterAlias